config/routes.rb
Rails.application.routes.draw do
  resources :attendees
  resources :events
  resources :users
  get "/pages/:page" => "pages#show"
  get '/join' => 'attendees#join'
  get '/leave' => 'attendees#leave'

  root "events#index"
  

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  	has_many :attendees
	has_many :users, through: :attendees

	belongs_to :user, foreign_key: :user_id

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :attendees
	has_many :events, through: :attendees , foreign_key: :user_id

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:show, :edit, :update, :destroy]

  # GET /attendees
  # GET /attendees.json
  def index
    @attendees = Attendee.all
  end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
  end

  # GET /attendees/new
  def new
  end
  
  def join
    attendee = Attendee.create(user_id: 1, event_id: 1)
    attendee.save
    redirect_to '/events/1'
  end
  
  def leave
    attendee = Attendee.find_by(user_id: 1)
    attendee.destroy
    redirect_to '/events/1'
  end

  # GET /attendees/1/edit
  def edit
  end

  # POST /attendees
  # POST /attendees.json
  def create
    @attendee = Attendee.new(attendee_params)

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to @attendee, notice: 'Attendee was successfully created.' }
        format.json { render :show, status: :created, location: @attendee }
      else
        format.html { render :new }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendees/1
  # PATCH/PUT /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to @attendee, notice: 'Attendee was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendee }
      else
        format.html { render :edit }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendee_params
      params.require(:attendee).permit(:event_id, :user_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:sport, :datetime, :location, :coordinates, :description, :capacity, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendees/_form.html.erb
<%= form_for(@attendee) do |f| %>
  <% if @attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% @attendee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :event_id %><br />
  <%= f.select :event_id, options_for_select(Event.all.map{|s|[s.sport, s.id]}) %>
  </div>
  <div class="field">
  <%= f.label :user_id %><br />
  <%= f.select :user_id, options_for_select(User.all.map{|s|[s.name, s.id]}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<h1>Editing Attendee</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendee %> |
<%= link_to 'Back', attendees_path %>

app/views/attendees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attendees</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td><%= attendee.event_id %></td>
        <td><%= attendee.user_id %></td>
        <td><%= link_to 'Show', attendee %></td>
        <td><%= link_to 'Edit', edit_attendee_path(attendee) %></td>
        <td><%= link_to 'Destroy', attendee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendee', new_attendee_path %>

app/views/attendees/new.html.erb
<h1>New Attendee</h1>

<%= render 'form' %>

<%= link_to 'Back', attendees_path %>

app/views/attendees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @attendee.event_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @attendee.user_id %>
</p>

<%= link_to 'Edit', edit_attendee_path(@attendee) %> |
<%= link_to 'Back', attendees_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sport %><br>
    <%= f.text_field :sport %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br>
    <%= f.datetime_select :datetime %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :coordinates %><br>
    <%= f.text_field :coordinates %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
  <%= f.label :user_id %><br />
  <%= f.select :user_id, options_for_select(User.all.map{|s|[s.name, s.id]}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<head>
    <title>Custom Markers</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:900" rel="stylesheet">
    <!-- Proxima Nova-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css">
    <!-- animate -->
    <script src="https://use.fontawesome.com/47a7c6d863.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
     /* Float shit over the map */

     #over_map { position: absolute; top: 10px; left: 10px; z-index: 99; }

    </style>
  </head>
  
  
  <body>
    
    
     <div id="map">  </div>

     <div id="over_map">
       
        <div class="btn btn-default" style="width:20%;border-radius:40px;height:5em;width:5em;color:#2b2b2b;" href="http://www.google.com" >

            <i class="fa fa-bars" style="font-size:2em;margin-top:32%;" aria-hidden="true"></i>

        </div>
        
        <!-- add event buttom -->
        <div class="btn btn-success" style="background-color:#ffcc5e;border-color:#ffcc5e;width:20%;border-radius:40px;height:5em;width:5em;" href="http://www.google.com" >

            <i class="fa fa-plus" style="font-size:2em;margin-top:32%;" aria-hidden="true"></i>

        </div>
    
    </div>
     
    
    
    
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: new google.maps.LatLng(25.3164447,51.4405631),
          mapTypeId: 'roadmap',
          mapTypeControl: false,
          
        });

        var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';
        var icons = {
          football: {
            icon: 'https://image.ibb.co/k85KeG/Soccer_icon.png'
          },
          volleyball: {
            icon: 'http://icons.iconarchive.com/icons/custom-icon-design/flatastic-10/32/Sport-volleyball-icon.png'
          },
          basketball: {
            icon: 'http://icons.iconarchive.com/icons/martin-berube/sport/32/Basketball-icon.png'
          }
        };

        var features = [
          {
            position: new google.maps.LatLng(25.3161925,51.4396189),
            type: 'basketball',
            url: "https://en.wikipedia.org/wiki/Basketball"
          },{
            position: new google.maps.LatLng(25.3141364,51.4410781),
            type: 'football',
            url: "https://en.wikipedia.org/wiki/Football"
          },{
            position: new google.maps.LatLng(25.3153585,51.431744),
            type: 'volleyball',
            url: "https://en.wikipedia.org/wiki/Volleyball"
          }
        ];

        // Create markers.
        features.forEach(function(feature) {
          var marker = new google.maps.Marker({
            position: feature.position,
            icon: icons[feature.type].icon,
            map: map,
            url: feature.url
          });
          google.maps.event.addListener(marker, 'click', function() {
            window.open(marker.url);
          });
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBGrLqiEMEB9N0zzv79tDUdhP-8bNznpvg&callback=initMap">
    </script>
  </body>
  
  
  




<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Sport</th>
      <th>Datetime</th>
      <th>Location</th>
      <th>Coordinates</th>
      <th>Description</th>
      <th>Capacity</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.sport %></td>
        <td><%= event.datetime %></td>
        <td><%= event.location %></td>
        <td><%= event.coordinates %></td>
        <td><%= event.description %></td>
        <td><%= event.capacity %></td>
        <td><%= event.user.name %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<head>
  <title>Home</title>
  <!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Roboto:900" rel="stylesheet">
  <!-- Proxima Nova-->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css">
  <!-- animate -->
  <script src="https://use.fontawesome.com/47a7c6d863.js"></script>
</head>

<body style="background-color:#fbfbfb;">




  <div class="animated FadeIn" > <!-- ########## Slide-in Animation Div ########### -->


  <div class="row" style="height:20%;margin-bottom:1em;">  <!-- ########## What Kind Text ########### -->

    <h2 style="font-size:3em;font-weight:800;white-space: nowrap;text-align:center;" class="animated FadeIn" >Basketball<span style="color:#ff5b5b;padding-left:5px;">.</span></h2>
    <h4 style="font-size:1.6em;white-space: nowrap;text-align:center;margin-top:-10px;color:#aaaaaa;" class="animated FadeIn" >HBKU Student Center</span></h4>

  </div>

</div>

  <div class="row" style="margin-left:21%;">  <!-- ########## Buttons ########### -->



  <div class="row" style="margin-left:0.3%;">


      <!--
      <button class="btn btn-default" style="border-radius: 15px;margin:1%;margin-right:1.5%;max-width:25%;max-height:15%;box-shadow: 2px 2px 5px #d6d6d6;" id="pitch">

    </button>
    -->

    <img src="https://image.ibb.co/jn0Pww/23596222_166372933949583_5219923459932422144_n.jpg" class="animated FadeInRight" alt="23596222_166372933949583_5219923459932422144_n" style="box-shadow: 4px 4px 5px #d6d6d6;border-radius: 15px;width:6.5em;height:6.5em;" border="0">
    <img src="https://image.ibb.co/jn0Pww/23596222_166372933949583_5219923459932422144_n.jpg" class="animated FadeInRight" alt="23596222_166372933949583_5219923459932422144_n" style="box-shadow: 4px 4px 5px #d6d6d6;border-radius: 15px;width:6.5em;height:6.5em;margin-left:2em;" border="0">


  </div>

  <div class="row" style="margin-left:0.3%;margin-top:5%;">


      <!--
      <button class="btn btn-default" style="border-radius: 15px;margin:1%;margin-right:1.5%;max-width:25%;max-height:15%;box-shadow: 2px 2px 5px #d6d6d6;" id="pitch">

    </button>
    -->

    <img src="https://image.ibb.co/jn0Pww/23596222_166372933949583_5219923459932422144_n.jpg" class="animated FadeInRight" alt="23596222_166372933949583_5219923459932422144_n" style="box-shadow: 4px 4px 5px #d6d6d6;border-radius: 15px;width:6.5em;height:6.5em;" border="0">
    <img src="https://image.ibb.co/jn0Pww/23596222_166372933949583_5219923459932422144_n.jpg" class="animated FadeInRight" alt="23596222_166372933949583_5219923459932422144_n" style="box-shadow: 4px 4px 5px #d6d6d6;border-radius: 15px;width:6.5em;height:6.5em;margin-left:2em;" border="0">


  </div>

  <div class="row" style="margin-left:0.3%;margin-top:5%;">


      <!--
      <button class="btn btn-default" style="border-radius: 15px;margin:1%;margin-right:1.5%;max-width:25%;max-height:15%;box-shadow: 2px 2px 5px #d6d6d6;" id="pitch">

    </button>
    -->

    <img src="https://image.ibb.co/jn0Pww/23596222_166372933949583_5219923459932422144_n.jpg" class="animated FadeInRight" alt="23596222_166372933949583_5219923459932422144_n" style="box-shadow: 4px 4px 5px #d6d6d6;border-radius: 15px;width:6.5em;height:6.5em;" border="0">


  </div>





  </div>
  <div class="row" style="text-align:center;">
    <h2 style="font-size:4em;font-family: 'Roboto', sans-serif;"> 4/5 </h2>
  </div>
  
    <div class="row" style="text-align:center;">
    <button class="btn btn-success" style="background-color:#ffcc5e;border-color:#ffcc5e;width:20%;border-radius:40px;height:5em;width:5em;" href="http://www.google.com" >
      <div class="row">
        <i class="fa fa-plus" style="font-size:2em;" aria-hidden="true"></i>
      </div>

    </button>
  </div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/chat.html.erb
<head>
    <title>Custom Markers</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:900" rel="stylesheet">
    <!-- Proxima Nova-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css">
    <!-- animate -->
    <script src="https://use.fontawesome.com/47a7c6d863.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">  
    
  </head>
  
  
  <body style="background-color:#fbfbfb;">
    
          <div class="btn btn-default" style="width:20%;border-radius:40px;height:3.5em;width:3.5em;background-color:#fbfbfb;border-color:#fbfbfb;margin-bottom:-2em;" onclick="location.href = '/';" >

            <i class="fa fa-chevron-left" style="font-size:1.7em;margin-top:32%;" aria-hidden="true"></i>

        </div>
        
    <div class="row" style="margin-top:2em;">
        <div class="col-xs-9">
            <div class="panel panel-default" style="border-radius:80px;width:95%;height:80%;margin-left:10%;margin-top:3%;">
              <div class="panel-body">
                  <h5 style="margin:0;"> hey guys would you like</h5>
                  
              </div>
            </div>
      </div>
      
      <div class="col-xs-2">      
        <img  src="https://image.ibb.co/jn0Pww/23596222_166372933949583_5219923459932422144_n.jpg" class="animated FadeInRight" alt="235" style="margin-top:0.4em;border-radius: 25px;width:3.5em;height:3.5em;" border="0">
        </div>
    </div>
    

    <div class="row" id="user2" style="display:none;">
        <div class="col-xs-9">
            <div class="panel panel-default" style="border-radius:80px;width:95%;height:80%;margin-left:10%;margin-top:3%;">
              <div class="panel-body">
                  <h5 style="margin:0;"> hey guys would you like</h5>
                  
              </div>
            </div>
      </div>
      
      <div class="col-xs-2">      
        <img  src="https://image.ibb.co/jn0Pww/23596222_166372933949583_5219923459932422144_n.jpg" class="animated FadeInRight" alt="235" style="margin-top:0.4em;border-radius: 25px;width:3.5em;height:3.5em;" border="0">
        </div>
    </div>
    
    <div class="row" id="user3" style="display:none;">
        
        <div class="col-xs-2">      
        </div>
        
        
        <div class="col-xs-9">
            <div class="panel panel-default" style="background-color:#fc7a6c;border-radius:80px;width:95%;height:80%;margin-right:10%;margin-left:-3em;;margin-top:3%;">
              <div class="panel-body">
                  <h5 style="margin:0;color:white;"> hey guys would you like</h5>
                  
              </div>
            </div>
      </div>
      
      
    </div>
    
    
    <div class="row" id="user4" style="display:none;">
        <div class="col-xs-9">
            <div class="panel panel-default" style="border-radius:80px;width:95%;height:80%;margin-left:10%;margin-top:3%;">
              <div class="panel-body">
                  <h5 style="margin:0;"> Sounds Great! can't wait!!</h5>
                  
              </div>
            </div>
      </div>
      
      <div class="col-xs-2">      
        <img  src="https://image.ibb.co/jn0Pww/23596222_166372933949583_5219923459932422144_n.jpg" class="animated FadeInRight" alt="235" style="margin-top:0.4em;border-radius: 25px;width:3.5em;height:3.5em;" border="0">
        </div>
    </div>
    
    
    <div class="row" id="user5" style="display:none;">
        <div class="col-xs-9">
            <div class="panel panel-default" style="border-radius:80px;width:95%;height:80%;margin-left:10%;margin-top:3%;">
              <div class="panel-body">
                  <h5 style="margin:0;"> 😂😂😂👌👌👌💯💯🔥🔥🔥🔥 </h5>
                  
              </div>
            </div>
      </div>
      
      <div class="col-xs-2">      
        <img  src="https://image.ibb.co/jn0Pww/23596222_166372933949583_5219923459932422144_n.jpg" class="animated FadeInRight" alt="235" style="margin-top:0.4em;border-radius: 25px;width:3.5em;height:3.5em;" border="0">
        </div>
    </div>
    
    <div class="row" style="position:absolute;bottom:0px;width:100%;margin-bottom:1em;">
        <div class="col-xs-9" style="width:80%;">
            <form>
            <input type="text" id="box" style="border-radius:15px;width:100%;height:2.5em;margin-left:10%;margin-top:3%;padding-left:1em;"> </input>
            </form>
      </div>
      
      <div class="col-xs-2" >      
      <a id = "send" name="name" class="btn btn-info" style="width:20%;border-radius:30px;height:3em;width:3em;padding:0.7em;padding-left:-0.7em;margin-left:1em;margin-top:0.2em;"> 
      <i class="fa fa-paper-plane" aria-hidden="true"></i>
      </a>
      </div>
    </div>
 
    
  </body>
  
  


  <script type="text/javascript">
  
  
    $(document).ready(function() {

      setTimeout(function(){$("#user2").show(300);},  3400);

      

        $("#send").click(function() {
            document.getElementById("box").value = "";
            $("#user3").show(500);
            setTimeout(function(){$("#user4").show(500);},  3400);
            setTimeout(function(){$("#user5").show(500);},  6400);
            });

      
    });
  
</script>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.avatar.url(:thumb) %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @user.avatar.url(:medium) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>